name: cancoin_wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path_provider: ^2.0.2
  pin_code_fields: ^7.2.0
  get: ^4.1.4
  carousel_slider: ^4.0.0
  splash_screen_view: ^3.0.0
  flutter_card_swipper: ^0.4.0
  image_picker: ^0.8.1+3
  web3dart: ^2.1.4
  bip32: ^2.0.0
  bip39: ^1.0.6
  hex: ^0.2.0
  http: ^0.13.3
  clipboard: ^0.1.3
  qr_flutter: ^4.0.0
  isolate: ^2.1.1
  fancy_bottom_navigation: ^0.3.3
  decimal: ^1.2.0
  qr_code_scanner: ^0.5.2
  cached_network_image: ^3.0.0
  shared_preferences: ^2.0.6
  share: ^2.0.4
  sqflite: ^2.0.0+3
  coingecko_dart: ^0.0.9
  provider: ^5.0.0
  webview_flutter: ^2.0.10
  url_launcher: ^6.0.9
  syncfusion_flutter_charts: ^19.2.48
  fl_chart: ^0.36.3
  font_awesome_flutter: ^9.1.0
  line_icons: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/environment/.env
    - assets/environment/.env_prod
    - assets/images/
    - assets/fonts/
    - assets/abi.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - weight: 700
    - family: Poppins SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - weight: 600
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - weight: 500
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/king_icon.png"