class PageNames{
  PageNames._();
  static const String init = '/';
  static const String board = '/board';
  static const String recover = '/recover';
  static const String randphrase = '/randphrase';
  static const String verifyphrase = '/verifyphrase';
  static const String successwallet = '/successwallet';
  static const String qrinfo = '/qrinfo';
  static const String dashbaord = '/dashboard';
  static const String backup = '/backup';
  static const String qrreader = '/qrreader';
  static const String sendToken = '/sendToen';
  static const String transferForm = '/transferForm';
  static const String receive = '/receive';
  static const String setting = '/setting';
  static const String language = '/language';
  static const String theme = '/theme';
  static const String security = '/security';
  static const String guard = '/guard';
  static const String createPinCode = '/createPinCode';
  static const String removePinCode = '/removePinCode';
  static const String signTx = '/signTx';
  static const String tokenList = '/tokenList';
  static const String walletconnect = '/walletconnect';
  static const String buy = '/buy';
  static const String txInfo = '/txInfo';
  static const String walletAccount = '/walletAccount';
  static const String editAccount = '/editAccount';
  static const String setNotification = '/setNotification';
}